services:

  frontend:
    container_name: frontend
    image: nginx
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      - my-app-network

  backend:
    container_name: backend
    build: ./backend/.
    restart: unless-stopped
    networks:
      - my-app-network

networks:
  my-app-network:
