services:
  frontend:
    container_name: frontend
    image: nginx
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: unless-stopped

  backend:
    container_name: backend
    build: ./backend/.
    ports:
      - "3000:3000"
    restart: unless-stopped

